/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.example.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WeatherMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4256917924559155169L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherMessage\",\"namespace\":\"org.example.avro\",\"fields\":[{\"name\":\"station_id\",\"type\":\"long\"},{\"name\":\"s_no\",\"type\":\"long\"},{\"name\":\"battery_status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"status_timestamp\",\"type\":\"long\"},{\"name\":\"weather\",\"type\":{\"type\":\"record\",\"name\":\"weather_fields\",\"fields\":[{\"name\":\"humidity\",\"type\":\"int\"},{\"name\":\"temperature\",\"type\":\"int\"},{\"name\":\"wind_speed\",\"type\":\"int\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WeatherMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WeatherMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WeatherMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WeatherMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WeatherMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WeatherMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WeatherMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WeatherMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WeatherMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long station_id;
  private long s_no;
  private java.lang.String battery_status;
  private long status_timestamp;
  private org.example.avro.weather_fields weather;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherMessage() {}

  /**
   * All-args constructor.
   * @param station_id The new value for station_id
   * @param s_no The new value for s_no
   * @param battery_status The new value for battery_status
   * @param status_timestamp The new value for status_timestamp
   * @param weather The new value for weather
   */
  public WeatherMessage(java.lang.Long station_id, java.lang.Long s_no, java.lang.String battery_status, java.lang.Long status_timestamp, org.example.avro.weather_fields weather) {
    this.station_id = station_id;
    this.s_no = s_no;
    this.battery_status = battery_status;
    this.status_timestamp = status_timestamp;
    this.weather = weather;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return station_id;
    case 1: return s_no;
    case 2: return battery_status;
    case 3: return status_timestamp;
    case 4: return weather;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: station_id = (java.lang.Long)value$; break;
    case 1: s_no = (java.lang.Long)value$; break;
    case 2: battery_status = value$ != null ? value$.toString() : null; break;
    case 3: status_timestamp = (java.lang.Long)value$; break;
    case 4: weather = (org.example.avro.weather_fields)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'station_id' field.
   * @return The value of the 'station_id' field.
   */
  public long getStationId() {
    return station_id;
  }


  /**
   * Sets the value of the 'station_id' field.
   * @param value the value to set.
   */
  public void setStationId(long value) {
    this.station_id = value;
  }

  /**
   * Gets the value of the 's_no' field.
   * @return The value of the 's_no' field.
   */
  public long getSNo() {
    return s_no;
  }


  /**
   * Sets the value of the 's_no' field.
   * @param value the value to set.
   */
  public void setSNo(long value) {
    this.s_no = value;
  }

  /**
   * Gets the value of the 'battery_status' field.
   * @return The value of the 'battery_status' field.
   */
  public java.lang.String getBatteryStatus() {
    return battery_status;
  }


  /**
   * Sets the value of the 'battery_status' field.
   * @param value the value to set.
   */
  public void setBatteryStatus(java.lang.String value) {
    this.battery_status = value;
  }

  /**
   * Gets the value of the 'status_timestamp' field.
   * @return The value of the 'status_timestamp' field.
   */
  public long getStatusTimestamp() {
    return status_timestamp;
  }


  /**
   * Sets the value of the 'status_timestamp' field.
   * @param value the value to set.
   */
  public void setStatusTimestamp(long value) {
    this.status_timestamp = value;
  }

  /**
   * Gets the value of the 'weather' field.
   * @return The value of the 'weather' field.
   */
  public org.example.avro.weather_fields getWeather() {
    return weather;
  }


  /**
   * Sets the value of the 'weather' field.
   * @param value the value to set.
   */
  public void setWeather(org.example.avro.weather_fields value) {
    this.weather = value;
  }

  /**
   * Creates a new WeatherMessage RecordBuilder.
   * @return A new WeatherMessage RecordBuilder
   */
  public static org.example.avro.WeatherMessage.Builder newBuilder() {
    return new org.example.avro.WeatherMessage.Builder();
  }

  /**
   * Creates a new WeatherMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherMessage RecordBuilder
   */
  public static org.example.avro.WeatherMessage.Builder newBuilder(org.example.avro.WeatherMessage.Builder other) {
    if (other == null) {
      return new org.example.avro.WeatherMessage.Builder();
    } else {
      return new org.example.avro.WeatherMessage.Builder(other);
    }
  }

  /**
   * Creates a new WeatherMessage RecordBuilder by copying an existing WeatherMessage instance.
   * @param other The existing instance to copy.
   * @return A new WeatherMessage RecordBuilder
   */
  public static org.example.avro.WeatherMessage.Builder newBuilder(org.example.avro.WeatherMessage other) {
    if (other == null) {
      return new org.example.avro.WeatherMessage.Builder();
    } else {
      return new org.example.avro.WeatherMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for WeatherMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherMessage>
    implements org.apache.avro.data.RecordBuilder<WeatherMessage> {

    private long station_id;
    private long s_no;
    private java.lang.String battery_status;
    private long status_timestamp;
    private org.example.avro.weather_fields weather;
    private org.example.avro.weather_fields.Builder weatherBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.example.avro.WeatherMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.station_id)) {
        this.station_id = data().deepCopy(fields()[0].schema(), other.station_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.s_no)) {
        this.s_no = data().deepCopy(fields()[1].schema(), other.s_no);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.battery_status)) {
        this.battery_status = data().deepCopy(fields()[2].schema(), other.battery_status);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status_timestamp)) {
        this.status_timestamp = data().deepCopy(fields()[3].schema(), other.status_timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.weather)) {
        this.weather = data().deepCopy(fields()[4].schema(), other.weather);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (other.hasWeatherBuilder()) {
        this.weatherBuilder = org.example.avro.weather_fields.newBuilder(other.getWeatherBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(org.example.avro.WeatherMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.station_id)) {
        this.station_id = data().deepCopy(fields()[0].schema(), other.station_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.s_no)) {
        this.s_no = data().deepCopy(fields()[1].schema(), other.s_no);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.battery_status)) {
        this.battery_status = data().deepCopy(fields()[2].schema(), other.battery_status);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status_timestamp)) {
        this.status_timestamp = data().deepCopy(fields()[3].schema(), other.status_timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.weather)) {
        this.weather = data().deepCopy(fields()[4].schema(), other.weather);
        fieldSetFlags()[4] = true;
      }
      this.weatherBuilder = null;
    }

    /**
      * Gets the value of the 'station_id' field.
      * @return The value.
      */
    public long getStationId() {
      return station_id;
    }


    /**
      * Sets the value of the 'station_id' field.
      * @param value The value of 'station_id'.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder setStationId(long value) {
      validate(fields()[0], value);
      this.station_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'station_id' field has been set.
      * @return True if the 'station_id' field has been set, false otherwise.
      */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'station_id' field.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder clearStationId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 's_no' field.
      * @return The value.
      */
    public long getSNo() {
      return s_no;
    }


    /**
      * Sets the value of the 's_no' field.
      * @param value The value of 's_no'.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder setSNo(long value) {
      validate(fields()[1], value);
      this.s_no = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 's_no' field has been set.
      * @return True if the 's_no' field has been set, false otherwise.
      */
    public boolean hasSNo() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 's_no' field.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder clearSNo() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'battery_status' field.
      * @return The value.
      */
    public java.lang.String getBatteryStatus() {
      return battery_status;
    }


    /**
      * Sets the value of the 'battery_status' field.
      * @param value The value of 'battery_status'.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder setBatteryStatus(java.lang.String value) {
      validate(fields()[2], value);
      this.battery_status = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'battery_status' field has been set.
      * @return True if the 'battery_status' field has been set, false otherwise.
      */
    public boolean hasBatteryStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'battery_status' field.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder clearBatteryStatus() {
      battery_status = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status_timestamp' field.
      * @return The value.
      */
    public long getStatusTimestamp() {
      return status_timestamp;
    }


    /**
      * Sets the value of the 'status_timestamp' field.
      * @param value The value of 'status_timestamp'.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder setStatusTimestamp(long value) {
      validate(fields()[3], value);
      this.status_timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status_timestamp' field has been set.
      * @return True if the 'status_timestamp' field has been set, false otherwise.
      */
    public boolean hasStatusTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status_timestamp' field.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder clearStatusTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'weather' field.
      * @return The value.
      */
    public org.example.avro.weather_fields getWeather() {
      return weather;
    }


    /**
      * Sets the value of the 'weather' field.
      * @param value The value of 'weather'.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder setWeather(org.example.avro.weather_fields value) {
      validate(fields()[4], value);
      this.weatherBuilder = null;
      this.weather = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'weather' field has been set.
      * @return True if the 'weather' field has been set, false otherwise.
      */
    public boolean hasWeather() {
      return fieldSetFlags()[4];
    }

    /**
     * Gets the Builder instance for the 'weather' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public org.example.avro.weather_fields.Builder getWeatherBuilder() {
      if (weatherBuilder == null) {
        if (hasWeather()) {
          setWeatherBuilder(org.example.avro.weather_fields.newBuilder(weather));
        } else {
          setWeatherBuilder(org.example.avro.weather_fields.newBuilder());
        }
      }
      return weatherBuilder;
    }

    /**
     * Sets the Builder instance for the 'weather' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public org.example.avro.WeatherMessage.Builder setWeatherBuilder(org.example.avro.weather_fields.Builder value) {
      clearWeather();
      weatherBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'weather' field has an active Builder instance
     * @return True if the 'weather' field has an active Builder instance
     */
    public boolean hasWeatherBuilder() {
      return weatherBuilder != null;
    }

    /**
      * Clears the value of the 'weather' field.
      * @return This builder.
      */
    public org.example.avro.WeatherMessage.Builder clearWeather() {
      weather = null;
      weatherBuilder = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WeatherMessage build() {
      try {
        WeatherMessage record = new WeatherMessage();
        record.station_id = fieldSetFlags()[0] ? this.station_id : (java.lang.Long) defaultValue(fields()[0]);
        record.s_no = fieldSetFlags()[1] ? this.s_no : (java.lang.Long) defaultValue(fields()[1]);
        record.battery_status = fieldSetFlags()[2] ? this.battery_status : (java.lang.String) defaultValue(fields()[2]);
        record.status_timestamp = fieldSetFlags()[3] ? this.status_timestamp : (java.lang.Long) defaultValue(fields()[3]);
        if (weatherBuilder != null) {
          try {
            record.weather = this.weatherBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("weather"));
            throw e;
          }
        } else {
          record.weather = fieldSetFlags()[4] ? this.weather : (org.example.avro.weather_fields) defaultValue(fields()[4]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WeatherMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<WeatherMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WeatherMessage>
    READER$ = (org.apache.avro.io.DatumReader<WeatherMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.station_id);

    out.writeLong(this.s_no);

    out.writeString(this.battery_status);

    out.writeLong(this.status_timestamp);

    this.weather.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.station_id = in.readLong();

      this.s_no = in.readLong();

      this.battery_status = in.readString();

      this.status_timestamp = in.readLong();

      if (this.weather == null) {
        this.weather = new org.example.avro.weather_fields();
      }
      this.weather.customDecode(in);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.station_id = in.readLong();
          break;

        case 1:
          this.s_no = in.readLong();
          break;

        case 2:
          this.battery_status = in.readString();
          break;

        case 3:
          this.status_timestamp = in.readLong();
          break;

        case 4:
          if (this.weather == null) {
            this.weather = new org.example.avro.weather_fields();
          }
          this.weather.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










