apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: elasticsearch
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
          #env:
           # - name: ELASTICSEARCH_HOST
           #   value: elasticsearch-kibana-service 
           # - name: ELASTICSEARCH_PORT
           #   value: "9200"
            
apiVersion: v1
kind: Service
metadata:
  name: elastic-service
spec:
  selector:
    app: elastic
  ports:
  - name: http
    port: 5000
    targetPort: 5000
