apiVersion: apps/v1
kind: Deployment
metadata:
  name: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: data
          image: datac
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-volume
              mountPath: /media/gad/mega/new
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: local-pvc 

